### PR TITLE
handle rental cancelation policies and rental cancelation policy items endpoints

### PR DESCRIPTION
**Pull request by Azdaroth**

### CODE REVIEW

**Comment by Azdaroth** [comment]
Requires merging PR from BS core first with API update.

**Comment by ZenCocoon** [comment]
How about the other CRUD actions?

**Comment by Azdaroth** [comment]
Right, `show` actions are missing, need to add it. No other actions are currently implemented in API as they haven't been needed so far.

**Comment by Azdaroth** [comment]
Added `show` actions.

**Comment by Mandaryn** [comment]
+1

**Comment by Mandaryn** [comment]
actually missing changelog info

**Comment by Azdaroth** [comment]
Added changelog.

**Pull request merged**
